version: '2.4'
services:
  dandelion_bootstrap:
    container_name: 'dandelion_bootstrap'
    image: 'openv2x/dandelion:columbia'
    environment:
      KOLLA_BOOTSTRAP: '\"\"'
    network_mode: 'host'
    volumes:
      - '/etc/dandelion/dandelion.conf:/etc/dandelion/dandelion.conf'
      - '/var/log/dandelion:/var/log/dandelion'
      - '/openv2x/data/bitmap:/openv2x/data/bitmap'
