version: '2.4'
services:
 dandelion_bootstrap:
  container_name: 'dandelion_bootstrap'
  image: 'openv2x/dandelion:albany'
  environment:
   KOLLA_BOOTSTRAP: '\"\"'
  network_mode: 'host'
  volumes:
   - '/etc/dandelion/dandelion.conf:/etc/dandelion/dandelion.conf'
   - '/var/log/dandelion:/var/log/dandelion'
